## NumPy

In [1]:
import numpy as np

**Initializing an Array**

In [2]:
# 1. Directly from data
arr1 = np.array([1, 2, 3, 4, 5])  # 一维数组
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 二维数组

In [34]:
# 2. With random or constant values
x = np.arange(10, 20, 2, dtype =  float)  
print (x)

# numpy.linspace 函数用于创建一个一维数组，
# 数组是一个等差数列构成的
a = np.linspace(0, 12, 7)
print(a)

# 设置元素全部是1的等差数列
a = np.linspace(1,1,10).reshape([2, 5])
print(a)

import numpy.matlib 

# numpy.matlib.zeros() 函数创建一个以 0 填充的矩阵
print (np.matlib.zeros((3,2)))

# numpy.matlib.ones()函数创建一个以 1 填充的矩阵
print (np.matlib.ones((5,1)))

# numpy.matlib.identity() 函数返回给定大小的单位矩阵
print (np.matlib.identity(5, dtype =  float))

# numpy.matlib.rand() 函数创建一个给定大小的矩阵，数据是随机填充的
print (np.matlib.rand(3,3))

[10. 12. 14. 16. 18.]
[ 0.  2.  4.  6.  8. 10. 12.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0.36164184 0.84634149 0.28138189]
 [0.8117014  0.51491549 0.79608742]
 [0.26056467 0.34552727 0.32652432]]


In [27]:
# 3. From Tensor
import torch 

t = torch.ones(5)
n = t.numpy()
n

array([1., 1., 1., 1., 1.], dtype=float32)

**Attributes of an Array**

In [3]:
print(arr1.shape)  # (5,)
print(arr2.dtype)  # int64
print(arr2.ndim)   # 2

(5,)
int32
2


### Operations on Arrays

**1. indexing and slicing:**

In [28]:
arr1 = np.array([1, 2, 3, 4, 5])  # 一维数组
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 二维数组

print(arr1[0])      # Accessing single element
print(arr2[:, 1:])  # Slicing
print(arr1[1: 4: 2])  # 从索引 1 开始到索引 4 停止，间隔为 2

1
[[2 3]
 [5 6]]
[2 4]


In [29]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])  
print (a[...,1])   # 第2列元素
print (a[1,...])   # 第2行元素
print (a[...,1:])  # 第2列及剩下的所有元素

[2 4 5]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]]


**2. 基本运算**

In [6]:
arr3 = arr1 + 10    # Element-wise addition
arr4 = np.sum(arr2) # Array-wise sum
print(arr3)
print(arr4)

[11 12 13 14 15]
21


**3. 矩阵操作:**

In [36]:
# Matrox Multiplication
matrix_product = np.matmul(arr2, arr2.T) 
matrix_product = arr2 @ arr2.T  # 和matmul等价
### matrix_product = np.dot(arr2, arr2.T) 
matrix_product

array([[14, 32],
       [32, 77]])

In [9]:
# Element-wise product
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result_array = array1 * array2
result_array

array([ 4, 10, 18])

**3.5 向量操作:**

In [35]:
print (np.inner(np.array([1,2,3]),np.array([0,1,0])))
# 等价于 1*0+2*1+3*0

2


In [37]:
print (np.dot(np.array([1,2,3]),np.array([0,1,0])))
# 等价于 1*0+2*1+3*0

2


**4. Array Functions:**

In [11]:
mean_val = np.mean(arr1)  # Mean
max_val = np.max(arr2)    # Maximum
print(mean_val, max_val)

3.0 6


**5. Broadcast**

In [30]:
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([0,1,2])
print(a + b)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
