## Tensors

A tensor on PyTorch has three attributes:

+ shape: the size of the tensor
+ data type: the type of data stored in the tensor
+ device: the device in which the tensor is stored

In [1]:
import torch
import numpy as np

print(torch.__version__)


if torch.cuda.is_available():
    device = torch.cuda.get_device_name(0)
    print("Current GPU:", device)
else:
    print("GPU is not available.")


2.2.1+cu121
Current GPU: NVIDIA GeForce RTX 4060 Laptop GPU


**Initializing a Tensor**

In [2]:
# 1.Directly from data
t = torch.tensor([[1, 2], [3, 4]]).cuda()
t

tensor([[1, 2],
        [3, 4]], device='cuda:0')

In [4]:
scalar = torch.tensor(7)
scalar.ndim

0

In [36]:
# 2.From a NumPy array
ndarray = np.array([0, 1, 2])
t = torch.from_numpy(ndarray).cuda()
t

tensor([0, 1, 2], device='cuda:0', dtype=torch.int32)

In [46]:
# 3.From another tensor
x_data = torch.tensor([[1, 2], [3, 4]]).cuda()
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[0, 0],
        [0, 0]], device='cuda:0') 

Random Tensor: 
 tensor([[0.8177, 0.1977],
        [0.7202, 0.0898]], device='cuda:0') 



In [43]:
# 4. With random or constant values
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
rand_tensor

tensor([[0.7703, 0.0066, 0.2875],
        [0.8999, 0.2358, 0.3046]])

In [131]:
torch.arange(10).reshape((2, 5))
torch.arange(10).reshape((2, -1))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

**Attributes of a Tensor**

In [40]:
tensor = torch.rand(3,4).cuda()

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cuda:0


### Operations on Tensors

**1. Standard numpy-like indexing and slicing:**

In [4]:
tensor = torch.ones(4, 5, 2)

# a = np.array([[1,2,3],[3,4,5],[4,5,6]])  
# tensor = torch.from_numpy(a)

print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Second column: {tensor[1, ...]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1, 2, 3], dtype=torch.int32)
First column: tensor([1, 3, 4], dtype=torch.int32)
Second column: tensor([3, 4, 5], dtype=torch.int32)
Last column: tensor([3, 5, 6], dtype=torch.int32)
tensor([[1, 0, 3],
        [3, 0, 5],
        [4, 0, 6]], dtype=torch.int32)


**2. Joining tensors**

In [73]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[[1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [0., 0.],
      

**3. Arithmetic operations**

In [80]:
np_array = np.array([[1, 2], [3, 4], [5, 6]])
tensor = torch.from_numpy(np_array)
print(tensor)

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32)


In [56]:
# Matrix operation 1: Matrix multiplication 
# This computes the matrix multiplication between two tensors.
y1 = tensor @ tensor.T
y1 = tensor.matmul(tensor.T)
y1

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]], dtype=torch.int32)

In [60]:
# Matrix operation 2: element-wise product
y2 = tensor * tensor
y2 = tensor.mul(tensor)
y2

tensor([[ 1,  4],
        [ 9, 16],
        [25, 36]], dtype=torch.int32)

**4. Single-element tensors**

In [64]:
np_array = np.array([[1, 2], [3, 4], [5, 6]])
tensor = torch.from_numpy(np_array)

agg = tensor.sum()
# agg_item = agg.item()
# print(agg_item, type(agg_item))
agg

tensor(21)

**5. In-place operations**

Operations that store the result into the operand are called in-place. They are denoted by a `_` suffix. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

In [65]:
np_array = np.array([[1, 2], [3, 4], [5, 6]])
tensor = torch.from_numpy(np_array)

print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32) 

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]], dtype=torch.int32)


### Bridge with NumPy

**Tensor to NumPy array**

In [66]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [67]:
# A change in the tensor reflects in the NumPy array.
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


**NumPy array to Tensor**

In [69]:
n = np.ones(5)
t = torch.from_numpy(n)

In [70]:
# Changes in the NumPy array reflects in the tensor.
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


## Cat, vstack and hstack

In [87]:
tensor1 = torch.tensor([[[7, 7, 7], [6, 6, 6]], [[4, 4, 4], [2, 2, 2]]])
tensor2 = torch.tensor([[[1, 0, 0], [0, 1, 0]], [[1, 0, 0], [0, 1, 0]]])

In [88]:
cat_tensor = torch.cat((tensor1, tensor2), dim=0)
# cat_tensor = torch.vstack((tensor1, tensor2)) # 垂直拼接，两者等价
print("Concatenated tensor along rows:\n", cat_tensor)

Concatenated tensor along rows:
 tensor([[[7, 7, 7],
         [6, 6, 6]],

        [[4, 4, 4],
         [2, 2, 2]],

        [[1, 0, 0],
         [0, 1, 0]],

        [[1, 0, 0],
         [0, 1, 0]]])


In [89]:
cat_tensor = torch.cat((tensor1, tensor2), dim=1)
# cat_tensor = torch.hstack((tensor1, tensor2)) # 水平拼接，两者等价
print("Concatenated tensor along columns:\n", cat_tensor)

Concatenated tensor along columns:
 tensor([[[7, 7, 7],
         [6, 6, 6],
         [1, 0, 0],
         [0, 1, 0]],

        [[4, 4, 4],
         [2, 2, 2],
         [1, 0, 0],
         [0, 1, 0]]])


In [92]:
cat_tensor = torch.cat((tensor1, tensor2), dim=2)
print("Concatenated tensor along columns:\n", cat_tensor)

Concatenated tensor along columns:
 tensor([[[7, 7, 7, 1, 0, 0],
         [6, 6, 6, 0, 1, 0]],

        [[4, 4, 4, 1, 0, 0],
         [2, 2, 2, 0, 1, 0]]])


### Tensor重塑和调整大小

In [5]:
import torch

# 创建一个3x3的随机张量
tensor = torch.rand(4, 3)
print("Original tensor:\n", tensor)

# 重塑张量为一个9元素的向量
reshaped_tensor = tensor.view(6, 2)
print("Reshaped tensor:\n", reshaped_tensor)

# 调整张量大小和维度
resized_tensor = tensor.resize_(1, 2, 1, 3)
print("Resized tensor:\n", resized_tensor)

# 展平张量为一维
flattened_tensor = torch.flatten(resized_tensor)
print("Flattened tensor:\n", flattened_tensor)

Original tensor:
 tensor([[0.2038, 0.3428, 0.9345],
        [0.9291, 0.7025, 0.6332],
        [0.0518, 0.1934, 0.4218],
        [0.3266, 0.5722, 0.7227]])
Reshaped tensor:
 tensor([[0.2038, 0.3428],
        [0.9345, 0.9291],
        [0.7025, 0.6332],
        [0.0518, 0.1934],
        [0.4218, 0.3266],
        [0.5722, 0.7227]])
Resized tensor:
 tensor([[[[0.2038, 0.3428, 0.9345]],

         [[0.9291, 0.7025, 0.6332]]]])
Flattened tensor:
 tensor([0.2038, 0.3428, 0.9345, 0.9291, 0.7025, 0.6332])


### Squeeze & unsqueeze

In [123]:
squeezed_tensor = torch.squeeze(resized_tensor)
print("Squeezed tensor:\n", squeezed_tensor)  # torch.Size([2, 3])

Squeezed tensor:
 tensor([[0.2920, 0.0085, 0.2651],
        [0.0969, 0.8603, 0.9257]])


In [124]:
# 在第0维度（行方向）上增加尺寸为1的维度
unsqueezed_tensor = torch.unsqueeze(squeezed_tensor, dim=0)
print("Unsqueezed tensor along dim=0:\n", unsqueezed_tensor) # torch.Size([1, 2, 3])

Unsqueezed tensor along dim=0:
 tensor([[[0.2920, 0.0085, 0.2651],
         [0.0969, 0.8603, 0.9257]]])


In [125]:
# 在第1维度（列方向）上增加尺寸为1的维度
unsqueezed_tensor = torch.unsqueeze(squeezed_tensor, dim=1)
print("Unsqueezed tensor along dim=1:\n", unsqueezed_tensor)  # torch.Size([2, 1, 3])

Unsqueezed tensor along dim=1:
 tensor([[[0.2920, 0.0085, 0.2651]],

        [[0.0969, 0.8603, 0.9257]]])


In [126]:
unsqueezed_tensor = torch.unsqueeze(squeezed_tensor, dim=2)
print("Unsqueezed tensor along dim=2:\n", unsqueezed_tensor)  # torch.Size([2, 3, 1])

Unsqueezed tensor along dim=2:
 tensor([[[0.2920],
         [0.0085],
         [0.2651]],

        [[0.0969],
         [0.8603],
         [0.9257]]])


In [127]:
# squeezed_tensor = torch.squeeze(unsqueezed_tensor)
# print("Squeezed tensor:\n", squeezed_tensor)  # torch.Size([2, 3])

Squeezed tensor:
 tensor([[0.2920, 0.0085, 0.2651],
        [0.0969, 0.8603, 0.9257]])
