In [1]:
import torch
import numpy as np
import torch.nn as nn
import torch.optim as optim
import torch.utils.data as Data

dtype = torch.FloatTensor

In [4]:
sentences = ["i like dog", "i love coffee", "i hate milk"]

word_list = " ".join(sentences).split()
vocab = list(set(word_list))
word2idx = {w: i for i, w in enumerate(vocab)}
idx2word = {i: w for i, w in enumerate(vocab)}
n_class = len(vocab)

# TextRNN Parameter
batch_size = 2
n_step = 2 # number of cells(= number of Step)
n_hidden = 5 # number of hidden units in one cell

In [15]:
def make_data(sentences):
    input_batch = []
    target_batch = []

    for sentence in sentences:
        word = sentence.split()
        input = [word2idx[n] for n in word[:-1]]  # 'i', 'like'
        target = word2idx[word[-1]]  # 'dog'
        
        input_batch.append(np.eye(n_class)[input])
        target_batch.append(target)

    return input_batch, target_batch

input_batch, target_batch = make_data(sentences)  # input:[1, 0] [1, 4] [1, 5] target: 2 6 3
input_batch, target_batch = torch.Tensor(input_batch), torch.LongTensor(target_batch)
dataset = Data.TensorDataset(input_batch, target_batch)
loader = Data.DataLoader(dataset, batch_size, True)

In [17]:
print(input_batch)
print(input_batch.shape)
print(np.eye(7)[[1, 2, 5]])

tensor([[[0., 1., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0.]],

        [[0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 0., 0.]],

        [[0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 1., 0.]]])
torch.Size([3, 2, 7])
[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]]


In [24]:
class TextRNN(nn.Module):
    def __init__(self):
        super(TextRNN, self).__init__()
        self.rnn = nn.RNN(input_size=n_class, hidden_size=n_hidden)
        self.fc = nn.Linear(n_hidden, n_class)
        
        
    def forward(self, hidden, X):
        # X: [batch_size, n_step, n_class]
        X = X.transpose(0, 1) # X : [n_step, batch_size, n_class]
        out, hidden = self.rnn(X, hidden)
        
        # out : [n_step, batch_size, num_directions(=1) * n_hidden]
        # hidden : [num_layers(=1) * num_directions(=1), batch_size, n_hidden]
        out = out[-1] # [batch_size, num_directions(=1) * n_hidden] ⭐
        
        out = self.fc(out)
        return out
    
model = TextRNN()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [25]:
# Training
for epoch in range(5000):
    for x, y in loader:
        # hidden : [num_layers * num_directions, batch, hidden_size]
        hidden = torch.zeros(1, x.shape[0], n_hidden) # h0
        # x : [batch_size, n_step, n_class]
        pred = model(hidden, x)

        # pred : [batch_size, n_class], y : [batch_size] (LongTensor, not one-hot)
        loss = criterion(pred, y)
    if (epoch + 1) % 1000 == 0:
        print('Epoch:', '%04d' % (epoch + 1), 'cost =', '{:.6f}'.format(loss))

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

Epoch: 1000 cost = 0.320235
Epoch: 2000 cost = 0.103191
Epoch: 3000 cost = 0.032607
Epoch: 4000 cost = 0.010275
Epoch: 5000 cost = 0.006935


In [26]:
input = [sentence.split()[:2] for sentence in sentences]
# Predict
hidden = torch.zeros(1, len(input), n_hidden)
predict = model(hidden, input_batch).data.max(1, keepdim=True)[1]
print([sen.split()[:2] for sen in sentences], '->', [idx2word[n.item()] for n in predict.squeeze()])

[['i', 'like'], ['i', 'love'], ['i', 'hate']] -> ['dog', 'coffee', 'milk']
